Repository imbrn/v8n, pull requests merged in 2018-07, with the labels that each got.

#68 Refactor validation object to make it immutable
  src/Context.js
  src/Modifier.js
  src/v8n.js
  src/v8n.test.js
Labels: Scope: API, Type: Change

#63 Overhaul documentation from the ground up
  .circleci/config.yml
  .gitignore
  README.md
  docs/.vuepress/config.js
  docs/Extending.md
  docs/Installation.md
  docs/README.md
  docs/Validation.md
  docs/api/README.md
  package.json
  scripts/deploy-docs.sh
  src/Context.js
  src/Modifier.js
  src/Rule.js
  src/ValidationException.js
  src/v8n.js
  src/v8n.test.js
  yarn.lock
Labels: Scope: Docs, Status: In Progress

#92 Add a CHANGELOG file
  CHANGELOG.md
Labels: Status: Accepted, Type: Maintenance

#83 Fix 'treat NaN as invalid number'
  CHANGELOG.md
  docs/api/README.md
  src/v8n.js
  src/v8n.test.js
Labels: Scope: Rule, Status: Accepted

#86 Add "any" rule for branching validations
  CHANGELOG.md
  docs/api/README.md
  src/v8n.js
  src/v8n.test.js
Labels: Scope: Rule, Status: Accepted

#95 Add a rule for optional validation
  CHANGELOG.md
  docs/Validation.md
  docs/api/README.md
  src/v8n.js
  src/v8n.test.js
Labels: Status: Accepted, Type: Feature Request

#99 Fix bug with "testAsync()" nesting causes for failed validations
  CHANGELOG.md
  src/Rule.js
  src/v8n.test.js
Labels: Priority: High, Scope: API, Status: Accepted, Type: Bug

#100 Prepare version 1.2.0
  CHANGELOG.md
  package.json
Labels: Status: Accepted
