Repository imbrn/v8n, pull requests merged in 2022-02, with the labels that each got.

#194 Release 1.4.0
  CHANGELOG.md
Labels: Status: Completed

#209 Github Action for publishing releases to NPM
  .github/workflows/npm-publish.yml
Labels: Priority: High, Scope: Build, Status: In Progress

#217 Manually deploy dispatching for GH Actions
  .github/workflows/npm-publish.yml
Labels: Priority: High, Status: In Progress

#218 Remove incorrect npm from yarn publish command
  .github/workflows/npm-publish.yml
  dist/v8n.browser.min.js.map
  dist/v8n.esm.browser.min.js.map
  dist/v8n.min.js.map
Labels: Priority: High

#219 Bump npm package version for release 1.4.0
  CHANGELOG.md
  package.json
Labels: Priority: High, Type: Maintenance

#222 Use correct path to vuepress dist
  .github/workflows/npm-publish.yml
Labels: Type: Bug, Scope: Docs

#223 Add optionalAsync rule
  CHANGELOG.md
  dist/v8n.amd.js
  dist/v8n.browser.js
  dist/v8n.browser.min.js
  dist/v8n.browser.min.js.map
  dist/v8n.cjs.js
  dist/v8n.esm.browser.js
  dist/v8n.esm.browser.min.js
  dist/v8n.esm.browser.min.js.map
  dist/v8n.esm.js
  dist/v8n.min.js
  dist/v8n.min.js.map
  dist/v8n.system.js
  dist/v8n.umd.js
  docs/api/README.md
  package.json
  src/v8n.js
  src/v8n.test.js
  types/v8n.d.ts
Labels: Scope: Rule, Status: Review Needed
